#!/usr/bin/env bash
# post-retro.sh — File GitHub issues from retro agent proposals and post summary.
#
# Runs on the host after sandbox cleanup. Working directory is the fullsend
# run output directory.
#
# Required env vars:
#   ORIGINATING_URL — HTML URL of the originating PR or issue
#   GH_TOKEN        — GitHub token with issues:write and pull_requests:write scope
#
# The agent writes its result to output/agent-result.json (relative to
# the iteration directory). This script finds the most recent iteration's output.

set -euo pipefail

: "${ORIGINATING_URL:?ORIGINATING_URL is required}"
: "${GH_TOKEN:?GH_TOKEN is required}"
echo "::add-mask::${GH_TOKEN}"

# Find the retro result JSON (same pattern as post-triage.sh).
RESULT_FILE=""
for dir in iteration-*/output; do
  if [[ -f "${dir}/agent-result.json" ]]; then
    RESULT_FILE="${dir}/agent-result.json"
  fi
done

if [[ -z "${RESULT_FILE}" ]]; then
  echo "ERROR: agent-result.json not found in any iteration output directory"
  exit 1
fi

echo "Reading retro result from: ${RESULT_FILE}"

# Validate JSON is parseable.
if ! jq empty "${RESULT_FILE}" 2>/dev/null; then
  echo "ERROR: ${RESULT_FILE} is not valid JSON"
  exit 1
fi

# Extract repo and number from ORIGINATING_URL.
# Accepts both /issues/N and /pull/N.
if [[ ! "${ORIGINATING_URL}" =~ ^https://github\.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/(issues|pull)/[0-9]+$ ]]; then
  echo "ERROR: ORIGINATING_URL does not match expected pattern: ${ORIGINATING_URL}"
  exit 1
fi
ORIGINATING_REPO=$(echo "${ORIGINATING_URL}" | sed -E 's#https://github.com/##; s#/(issues|pull)/.*##')
ORIGINATING_NUMBER=$(basename "${ORIGINATING_URL}")

echo "Originating: ${ORIGINATING_REPO}#${ORIGINATING_NUMBER}"

# File an issue for each proposal.
PROPOSAL_COUNT=$(jq '.proposals | length' "${RESULT_FILE}")
echo "Found ${PROPOSAL_COUNT} proposal(s)"

# Validate all proposals before filing any to avoid partial state.
for i in $(seq 0 $((PROPOSAL_COUNT - 1))); do
  TR=$(jq -r ".proposals[$i].target_repo" "${RESULT_FILE}")
  if [[ ! "${TR}" =~ ^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$ ]]; then
    echo "ERROR: proposal[$i].target_repo is not a valid owner/repo: ${TR}"
    exit 1
  fi
  TI=$(jq -r ".proposals[$i].title // empty" "${RESULT_FILE}")
  if [[ -z "${TI}" ]]; then
    echo "ERROR: proposal[$i].title is missing or empty"
    exit 1
  fi
  jq -e ".proposals[$i] | .what_happened and .what_could_go_better and .proposed_change and .validation_criteria" "${RESULT_FILE}" >/dev/null 2>&1 || {
    echo "ERROR: proposal[$i] is missing required fields"
    exit 1
  }
done
echo "All ${PROPOSAL_COUNT} proposal(s) validated"

# Process retractions before filing new proposals.
RETRACTION_COUNT=$(jq '.retractions // [] | length' "${RESULT_FILE}")
RETRACTION_LINKS=""
if [[ "${RETRACTION_COUNT}" -gt 0 ]]; then
  echo "Found ${RETRACTION_COUNT} retraction(s)"

  for i in $(seq 0 $((RETRACTION_COUNT - 1))); do
    R_REPO=$(jq -r ".retractions[$i].target_repo" "${RESULT_FILE}")
    R_NUMBER=$(jq -r ".retractions[$i].issue_number" "${RESULT_FILE}")
    R_REASON=$(jq -r ".retractions[$i].reason" "${RESULT_FILE}")

    # Validate target_repo format.
    if [[ ! "${R_REPO}" =~ ^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$ ]]; then
      echo "::warning::retraction[$i]: invalid target_repo '${R_REPO}', skipping"
      continue
    fi

    # Fetch issue to verify state and authorship.
    if ! ISSUE_JSON=$(gh api "repos/${R_REPO}/issues/${R_NUMBER}" 2>&1); then
      echo "::warning::retraction[$i]: could not fetch ${R_REPO}#${R_NUMBER}: ${ISSUE_JSON}"
      continue
    fi

    # Skip if already closed.
    ISSUE_STATE=$(echo "${ISSUE_JSON}" | jq -r '.state')
    if [[ "${ISSUE_STATE}" == "closed" ]]; then
      echo "retraction[$i]: ${R_REPO}#${R_NUMBER} is already closed, skipping"
      continue
    fi

    # Verify the issue was filed by the retro agent (check for signature in body).
    ISSUE_BODY=$(echo "${ISSUE_JSON}" | jq -r '.body // ""')
    if [[ "${ISSUE_BODY}" != *"_Generated by retro agent from "* ]]; then
      echo "::warning::retraction[$i]: ${R_REPO}#${R_NUMBER} was not filed by the retro agent, skipping"
      continue
    fi

    # Post retraction comment.
    RETRACT_COMMENT="This issue is being retracted by a subsequent retro run that identified the original analysis as incorrect.

**Reason:** ${R_REASON}

See the correcting retro context: ${ORIGINATING_URL}

---
_Retracted by retro agent_"

    echo "Retracting ${R_REPO}#${R_NUMBER}: ${R_REASON}"
    if ! jq -nc --arg body "${RETRACT_COMMENT}" '{body: $body}' | gh api \
      "repos/${R_REPO}/issues/${R_NUMBER}/comments" \
      --input - >/dev/null 2>&1; then
      echo "::warning::retraction[$i]: failed to comment on ${R_REPO}#${R_NUMBER}"
      continue
    fi

    # Close the issue.
    if ! gh issue close "${R_NUMBER}" --repo "${R_REPO}" --reason "not planned" 2>&1; then
      echo "::warning::retraction[$i]: failed to close ${R_REPO}#${R_NUMBER}"
      continue
    fi

    echo "Retracted: ${R_REPO}#${R_NUMBER}"
    RETRACTION_LINKS="${RETRACTION_LINKS}- Retracted [${R_REPO}#${R_NUMBER}](https://github.com/${R_REPO}/issues/${R_NUMBER}): ${R_REASON}
"
  done
fi

ISSUE_LINKS=""
for i in $(seq 0 $((PROPOSAL_COUNT - 1))); do
  TARGET_REPO=$(jq -r ".proposals[$i].target_repo" "${RESULT_FILE}")
  TITLE=$(jq -r ".proposals[$i].title" "${RESULT_FILE}")

  # Build the issue body from the four sections.
  BODY=$(jq -r --arg url "${ORIGINATING_URL}" "
    .proposals[$i] |
    \"## What happened\n\n\" + .what_happened +
    \"\n\n## What could go better\n\n\" + .what_could_go_better +
    \"\n\n## Proposed change\n\n\" + .proposed_change +
    \"\n\n## Validation criteria\n\n\" + .validation_criteria +
    \"\n\n---\n_Generated by retro agent from \" + \$url + \"_\"
  " "${RESULT_FILE}")

  # TODO(#833): Remove this warning once per-repo customization is stable.
  # Depends on: #195, #179, #419, PR #792, PR #799.
  if [[ "${TARGET_REPO}" == */.fullsend ]]; then
    echo "::warning::proposal[$i] targets a .fullsend repo (${TARGET_REPO}). Filing in .fullsend repos is discouraged until per-repo customization patterns are stable. Consider filing in the source repo or fullsend-ai/fullsend upstream instead."
  fi

  echo "Filing issue in ${TARGET_REPO}: ${TITLE}"
  if ! ISSUE_URL=$(gh issue create \
    --repo "${TARGET_REPO}" \
    --title "${TITLE}" \
    --body "${BODY}" 2>&1); then
    echo "ERROR: failed to create issue in ${TARGET_REPO}: ${ISSUE_URL}"
    exit 1
  fi

  echo "Created: ${ISSUE_URL}"
  ISSUE_LINKS="${ISSUE_LINKS}- [${TITLE}](${ISSUE_URL}) (in \`${TARGET_REPO}\`)
"
done

# Post summary comment on the originating PR/issue.
# Uses REST API (not gh issue comment) for consistency. Note: despite being
# an "issues" endpoint, GitHub requires pull_requests:write when the target
# number is a PR. See https://github.com/orgs/community/discussions/26644
SUMMARY=$(jq -r '.summary // empty' "${RESULT_FILE}")
if [[ -z "${SUMMARY}" ]]; then
  echo "ERROR: .summary is missing or empty in agent result"
  exit 1
fi

COMMENT="${SUMMARY}"
if [[ "${PROPOSAL_COUNT}" -gt 0 ]]; then
  COMMENT=$(printf '%s\n\n### Proposals filed\n\n%s' "${COMMENT}" "${ISSUE_LINKS}")
fi
if [[ -n "${RETRACTION_LINKS}" ]]; then
  COMMENT=$(printf '%s\n\n### Retractions\n\n%s' "${COMMENT}" "${RETRACTION_LINKS}")
fi

echo "Posting summary comment on ${ORIGINATING_REPO}#${ORIGINATING_NUMBER}"
jq -nc --arg body "${COMMENT}" '{body: $body}' | gh api \
  "repos/${ORIGINATING_REPO}/issues/${ORIGINATING_NUMBER}/comments" \
  --input -

echo "Post-retro complete."
