package tests

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

/*
MCP Configuration Drift Problem Document Validation Tests

STP Reference: outputs/stp/GH-17/GH-17_test_plan.md
STD Reference: outputs/std/GH-17/GH-17_test_description.yaml
Jira: GH-17

Generated by QualityFlow test-generator
*/

var _ = Describe("[GH-17] MCP Config Drift Problem Document Validation", func() {

	// ---------------------------------------------------------------
	// Scenario 001: Cross-reference link validation
	// Priority: P0 | MVP: true
	// ---------------------------------------------------------------
	Context("cross-reference link validation", Ordered, func() {
		var docContent []byte
		var err error

		BeforeAll(func() {
			docContent, err = os.ReadFile("docs/problems/mcp-config-drift.md")
			ExpectWithOffset(1, err).NotTo(HaveOccurred(),
				"Failed to read problem document docs/problems/mcp-config-drift.md")
		})

		It("[test_id:TS-GH-17-001] should verify all cross-reference links resolve to existing files", func() {
			// Extract relative markdown links: [text](relative/path)
			// Filter out external URLs (http://, https://) and anchor-only links (#)
			linkRegex := regexp.MustCompile(`\[([^\]]+)\]\(([^)]+)\)`)
			matches := linkRegex.FindAllStringSubmatch(string(docContent), -1)

			docDir := filepath.Dir("docs/problems/mcp-config-drift.md")

			var relativeLinks []string
			for _, match := range matches {
				linkTarget := match[2]
				// Skip external URLs and anchor-only links
				if strings.HasPrefix(linkTarget, "http://") ||
					strings.HasPrefix(linkTarget, "https://") ||
					strings.HasPrefix(linkTarget, "#") {
					continue
				}
				// Strip anchor fragments from relative links
				if idx := strings.Index(linkTarget, "#"); idx > 0 {
					linkTarget = linkTarget[:idx]
				}
				relativeLinks = append(relativeLinks, linkTarget)
			}

			Expect(relativeLinks).NotTo(BeEmpty(),
				"Document should contain at least one relative file link")

			for _, link := range relativeLinks {
				resolvedPath := filepath.Join(docDir, link)
				_, statErr := os.Stat(resolvedPath)
				ExpectWithOffset(1, statErr).NotTo(HaveOccurred(),
					"Cross-reference link target not found: %s (resolved to %s)", link, resolvedPath)
			}
		})
	})

	// ---------------------------------------------------------------
	// Scenario 002: README index entry validation
	// Priority: P0 | MVP: true
	// ---------------------------------------------------------------
	Context("README index entry validation", Ordered, func() {
		var readmeContent []byte
		var err error

		BeforeAll(func() {
			readmeContent, err = os.ReadFile("README.md")
			ExpectWithOffset(1, err).NotTo(HaveOccurred(),
				"Failed to read README.md")
		})

		It("[test_id:TS-GH-17-002] should verify README links to docs/problems/mcp-config-drift.md", func() {
			Expect(strings.Contains(string(readmeContent),
				"docs/problems/mcp-config-drift.md")).To(BeTrue(),
				"README.md should contain a link to the MCP config drift problem document")

			_, err = os.Stat("docs/problems/mcp-config-drift.md")
			ExpectWithOffset(1, err).NotTo(HaveOccurred(),
				"Problem document file should exist at docs/problems/mcp-config-drift.md")
		})
	})

	// ---------------------------------------------------------------
	// Scenario 003: Security component reference validation
	// Priority: P1 | MVP: false
	// ---------------------------------------------------------------
	Context("security component reference validation", Ordered, func() {
		var docContent []byte
		var err error

		BeforeAll(func() {
			docContent, err = os.ReadFile("docs/problems/mcp-config-drift.md")
			ExpectWithOffset(1, err).NotTo(HaveOccurred(),
				"Failed to read problem document")
		})

		It("[test_id:TS-GH-17-003] should verify references to security components match codebase", func() {
			content := string(docContent)

			Expect(strings.Contains(content,
				"ToolAllowlistPreToolHook")).To(BeTrue(),
				"Document should reference ToolAllowlistPreToolHook")

			Expect(strings.Contains(content,
				"SSRFPreToolHook")).To(BeTrue(),
				"Document should reference SSRFPreToolHook")

			Expect(strings.Contains(content,
				"GenerateClaudeSettings")).To(BeTrue(),
				"Document should reference GenerateClaudeSettings")
		})
	})

	// ---------------------------------------------------------------
	// Scenario 004: Document structure validation
	// Priority: P2 | MVP: false
	// ---------------------------------------------------------------
	Context("document structure validation", Ordered, func() {
		var docContent []byte
		var err error

		BeforeAll(func() {
			docContent, err = os.ReadFile("docs/problems/mcp-config-drift.md")
			ExpectWithOffset(1, err).NotTo(HaveOccurred(),
				"Failed to read problem document")
		})

		It("[test_id:TS-GH-17-004] should verify document contains required sections", func() {
			content := strings.ToLower(string(docContent))

			Expect(strings.Contains(content, "problem")).To(BeTrue(),
				"Document should contain a problem statement section")

			Expect(strings.Contains(content, "attack")).To(BeTrue(),
				"Document should contain an attack scenarios section")

			Expect(strings.Contains(content, "defense")).To(BeTrue(),
				"Document should contain a defense considerations section")

			Expect(strings.Contains(content, "open question")).To(BeTrue(),
				"Document should contain an open questions section")
		})
	})

	// ---------------------------------------------------------------
	// Scenario 005: Security documentation cross-reference integrity
	// Priority: P0 | MVP: true
	// ---------------------------------------------------------------
	Context("security documentation cross-reference integrity", Ordered, func() {
		var docContent []byte
		var err error

		BeforeAll(func() {
			docContent, err = os.ReadFile("docs/problems/mcp-config-drift.md")
			ExpectWithOffset(1, err).NotTo(HaveOccurred(),
				"Failed to read problem document")
		})

		It("[test_id:TS-GH-17-005] should verify links to security-threat-model.md, agent-architecture.md, and ADR 0017 resolve correctly", func() {
			content := string(docContent)

			// Verify security-threat-model.md is referenced
			Expect(strings.Contains(content,
				"security-threat-model")).To(BeTrue(),
				"Document should reference security-threat-model.md")

			// Verify agent-architecture.md is referenced
			Expect(strings.Contains(content,
				"agent-architecture")).To(BeTrue(),
				"Document should reference agent-architecture.md")

			// Verify ADR 0017 is referenced
			Expect(strings.Contains(content,
				"0017")).To(BeTrue(),
				"Document should reference ADR 0017")
		})
	})

	// ---------------------------------------------------------------
	// Scenario 006: Existing defense mechanism accuracy
	// Priority: P1 | MVP: false
	// ---------------------------------------------------------------
	Context("existing defense mechanism accuracy", Ordered, func() {
		var docContent []byte
		var err error

		BeforeAll(func() {
			docContent, err = os.ReadFile("docs/problems/mcp-config-drift.md")
			ExpectWithOffset(1, err).NotTo(HaveOccurred(),
				"Failed to read problem document")
		})

		It("[test_id:TS-GH-17-006] should verify description of existing defense mechanisms matches current implementation", func() {
			content := strings.ToLower(string(docContent))

			// Verify SSRF validator is mentioned
			Expect(strings.Contains(string(docContent), "SSRF")).To(BeTrue(),
				"Document should describe SSRF validation as an existing defense")

			// Verify tool allowlist hook is mentioned
			Expect(strings.Contains(content, "allowlist")).To(BeTrue(),
				"Document should describe tool allowlist as an existing defense")

			// Verify credential isolation is mentioned
			Expect(strings.Contains(content, "credential")).To(BeTrue(),
				"Document should describe credential isolation as an existing defense")
		})
	})

	// ---------------------------------------------------------------
	// Scenario 007: [NEGATIVE] Broken cross-reference detection
	// Priority: P2 | MVP: false
	// ---------------------------------------------------------------
	Context("[NEGATIVE] broken cross-reference detection", Ordered, func() {
		It("[test_id:TS-GH-17-007] should detect broken links when a cross-referenced document is missing", func() {
			_, err := os.Stat("docs/problems/non-existent-doc-for-negative-test.md")
			Expect(err).To(HaveOccurred(),
				"os.Stat should return an error for a non-existent file")
			Expect(os.IsNotExist(err)).To(BeTrue(),
				"Error should indicate file does not exist")
		})
	})
})
